
### 
get http://localhost:4000/contact
### POST request
post http://localhost:4000/contact
Content-Type: application/json
{
    "firstname": "Logan",
    "lasName": "Nguyen",
    "email": "lgad31vn@gmail.com",
    "company": "zinc10",
    "phone": "3002223232"
}

###
put http://localhost:4000/contact/1
###
delete http://localhost:4000/contact/1
